# Generated by Django 3.0.7 on 2021-11-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ccnumber',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='secnumber',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
