# Generated by Django 3.0.7 on 2021-11-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20211103_2334'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BankApiForm',
        ),
    ]
